apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: sonarr
spec:
  storageClassName: kenobi-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
