apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: sonarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarr.apps.home.sundland.net`)
      services:
        - name: sonarr
          port: 8989
          scheme: http
  tls: { }
---

