
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: talos-pa-w1-v1
  namespace: openebs
spec:
  node: talos-pa-w1
  disks: ["aio:///dev/vdb"]
  topology:
    labelled:
      zpool: kenobi

---

apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: talos-pa-w1-v2
  namespace: openebs
spec:
  node: talos-pa-w1
  disks: ["aio:///dev/vdc"]
  topology:
    labelled:
      zpool: vader
