apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unpackerr-config
  namespace: unpackerr
spec:
  storageClassName: kenobi-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
