#
# creates a storageclass (and makes it default) using the app-pool diskpool with 2 replicated PVs
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: apps-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  protocol: nvmf
  repl: "2"
  fsType: "xfs"
  thin: "true"
  allowVolumeExpansion: "true"
  poolAffinityTopologyLabel: |
    drivetype: nvme
provisioner: io.openebs.csi-mayastor
