apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: radarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.apps.home.sundland.net`)
      services:
        - name: radarr
          port: 7878
          scheme: http
  tls: { }
---

