apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
spec:
  storageClassName: kenobi-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
