apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
  namespace: recyclarr
spec:
  storageClassName: kenobi-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
