nextcloud:
  # Initial Credentials
  credentials:
    initialAdminUser: admin
    initialAdminPassword: changeme
  # General settings
  general:
    default_phone_region: US
    # IP used for exposing nextcloud,
    # often the loadbalancer IP
    accessIP: "10.6.64.50"
    # Allows Nextcloud to connect to unsecure (http) endpoints
    force_enable_allow_local_remote_servers: false
  # File settings
  files:
    shared_folder_name: Shared
    max_chunk_size: 10485760
  # Expiration settings
  expirations:
    activity_expire_days: 90
    trash_retention_obligation: auto
    versions_retention_obligation: auto
  # Previews settings
  previews:
    enabled: true
    # It will also deploy the container
    imaginary: true
    cron: true
    schedule: "*/30 * * * *"
    max_x: 2048
    max_y: 2048
    max_memory: 1024
    max_file_size_image: 50
    # Setting for Imaginary
    max_allowed_resolution: 18.0
    jpeg_quality: 60
    square_sizes: 32 256
    width_sizes: 256 384
    height_sizes: 256
    # Casings are important
    # https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1269
    # Only the last part of the provider is needed
    providers:
      - PNG
      - JPEG
      - BMP
      - GIF
      - MP3
      - OpenDocument
      - TXT
      - XBitmap
      - PDF
      - Photoshop
      - MSOffice2003
      - MSOffice2007
      - Movie
      - Postscript
      - StarOffice
      - SVC
      - TIFF
  # Logging settings
  logging:
    log_level: 2
    log_file: /var/www/html/data/logs/nextcloud.log
    log_audit_file: /var/www/html/data/logs/audit.log
    log_date_format: d/m/Y H:i:s
  # ClamAV settings
  clamav:
    # It will also deploy the container
    # Note that this runs as root
    enabled: false
    stream_max_length: 26214400
    file_max_size: -1
    infected_action: only_log
  # Notify Push settings
  notify_push:
    # It will also deploy the container
    enabled: true
  # PHP settings
  php:
    memory_limit: 4G
    upload_limit: 10G
    pm_max_children: 180
    pm_start_servers: 18
    pm_min_spare_servers: 12
    pm_max_spare_servers: 30
  opcache:
    interned_strings_buffer: 32
    max_accelerated_files: 10000
    memory_consumption: 128
    revalidate_freq: 60
    jit_buffer_size: 128

persistence:
  config:
    type: pvc
    size: 100Mi
    storageClass: vader-replicated
    retain: true

  html:
    type: pvc
    size: 10Gi
    storageClass: kenobi-replicated
    retain: true

  data:
    enabled: true
    type: nfs
    server: 10.6.64.10
    path: /mnt/vader/nextcloud30

      #  data-old:
      #    enabled: true
      # type: nfs
      # server: 10.6.64.10
      # path: /mnt/vader/nextcloud
      # targetSelector:
      #main:
      #  main:
      #    mountPath: /mnt/nextcloud-old

      #backup:
    #enabled: true
      #type: nfs
      #server: 10.6.64.10
      #path: /mnt/vader/backups/nextcloud
      #targetSelector:
      #main:
        # main:
          #   mountPath: /backup
            # nextcloud-cron:
        #        nextcloud-cron:
          #          mountPath: /backup

cnpg:
  main:
    database: nextcloud
    owner: nextcloud
    password: vtAQTs1onX1IRlnNmnh88mES2p2ELnxdSuNwu1WDZOko30aG0Z
    cluster:
      instances: 2
      storage:
        size: 20Gi
        storageClass: kenobi-single
        pvcRetain: true
        labels:
          velero.io/exclude-from-backup: "true"
      walStorage:
        size: 20Gi
        storageClass: kenobi-single
        pvcRetain: true
        labels:
          velero.io/exclude-from-backup: "true"

    #
    # RECOVERY
    # set
    #   .cnpg.main.mode: recovery
    #   .cnpg.main.recovery.revision: <value or backups.revision>
    #   .cnpg.main.backups.revision: <current value + 1>
    mode: standalone
    backups:
      enabled: true
      revision: "1"
      encryption:
        enabled: false

      scheduledBackups:
      - name: daily-backup
        schedule: "0 20 7 * * *"  # backups at UTC +0500 from EST
        backupOwnerReference: self
        immediate: true
        suspend: false

      credentials: ""   # replaced by setup script

    recovery:
      credentials: "" # replaced by setup script

redis:
  enabled: true
  includeCommon: true
  username: default

portal:
  open:
    enabled: true

ingressMiddlewares:
  traefik:
    nextcloud-redirect:
      enabled: false
      type: redirectRegex
      data:
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"

ingress:
  main:
    enabled: true
    required: false
    hosts: []

    tls: 
      - hosts: []
        # secretName: nextcloud-tls-0

    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt-prod

      traefik:
        entrypoints:
          - websecure
        forceTLS: true
