#
# configures the traefik-tcp pod to use app-pool and specific IP address
service:
  tcp:
    annotations:
      metallb.io/address-pool: app-pool
      metallb.io/loadBalancerIPs: 10.6.64.50

#
# sets the default certificate to the one created by clusterissuer
#    certificate-issuer-<name>
tlsStore:
  default:
    defaultCertificate:
      secretName: certificate-issuer-apps-cluster-cert
