apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prowlarr.apps.home.sundland.net`)
      services:
        - name: prowlarr
          port: 9696
          scheme: http
  tls: { }
---

