apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: prowlarr
spec:
  storageClassName: kenobi-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
