apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  storageClassName: kenobi-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
