apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`qbittorrent.apps.home.sundland.net`)
      services:
        - name: qbittorrent
          port: 10095
          scheme: http
  tls: { }
---

