#
# kenobi-replicated: creates a storageclass on our NVME disks with 2x replication
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kenobi-replicated
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  protocol: nvmf
  repl: "2"
  fsType: "xfs"
  thin: "true"
  allowVolumeExpansion: "true"
  poolAffinityTopologyLabel: |
    zpool: kenobi
provisioner: io.openebs.csi-mayastor
