#
# kenobi-single: creates a storageclass on our NVME disks without replication
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kenobi-single
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  protocol: nvmf
  repl: "1"
  fsType: "xfs"
  thin: "true"
  allowVolumeExpansion: "true"
  poolAffinityTopologyLabel: |
    zpool: kenobi
provisioner: io.openebs.csi-mayastor
