#
# vader-single: creates a storageclass on our HDD pool with no replication
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vader-single
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  protocol: nvmf
  repl: "1"
  fsType: "xfs"
  thin: "true"
  allowVolumeExpansion: "true"
  poolAffinityTopologyLabel: |
    zpool: vader
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Retain
allowVolumeExpansion: true
