apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: daily
spec:
  disabled: false
  claimSelector:
    matchLabels:
      snapshotschedule: daily
  retention:
    expires: "336h"  # 14 days
  schedule: "0 5 * * *" # midnight ETC
  snapshotTemplate:
    labels:
      snapshotschedule: daily

---
